ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "show_gifs" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Post"
ADD COLUMN IF NOT EXISTS "gifUrl" TEXT,
ADD COLUMN IF NOT EXISTS "gifAlt" TEXT;

ALTER TABLE "Comment"
ADD COLUMN IF NOT EXISTS "gifUrl" TEXT,
ADD COLUMN IF NOT EXISTS "gifAlt" TEXT;

ALTER TABLE "ArticleComment"
ADD COLUMN IF NOT EXISTS "gifUrl" TEXT,
ADD COLUMN IF NOT EXISTS "gifAlt" TEXT;
