apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-community-uploads
  namespace: devops-community
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
