apiVersion: v1
kind: Service
metadata:
  name: devops-community-api
  namespace: devops-community
spec:
  selector:
    app: devops-community-api
  ports:
    - name: http
      port: 4000
      targetPort: http
