apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community
  namespace: devops-community
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: devops-community
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - community.example.com
      secretName: community-example-tls
  rules:
    - host: community.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
