apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: devopshub
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: devopshub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
