apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: devops-hub
  labels:
    app.kubernetes.io/name: devops-hub-platform
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.observability.svc.cluster.local:4318"
  REDIS_HOST: "replace-me"
  REDIS_PORT: "6379"
  API_UPSTREAM_URL: "http://api-gateway.devops-hub.svc.cluster.local"
  COMMUNITY_API_URL: "http://community-api.devops-hub.svc.cluster.local"
  NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
