apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - community-api-deployment.yaml
  - community-api-service.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - api-gateway-hpa.yaml
  - api-gateway-pdb.yaml
  - auth-service-deployment.yaml
  - auth-service-service.yaml
  - auth-service-hpa.yaml
  - auth-service-pdb.yaml
  - profile-service-deployment.yaml
  - profile-service-service.yaml
  - profile-service-hpa.yaml
  - profile-service-pdb.yaml
  - media-service-deployment.yaml
  - media-service-service.yaml
  - media-service-hpa.yaml
  - media-service-pdb.yaml
  - notification-service-deployment.yaml
  - notification-service-service.yaml
  - notification-service-hpa.yaml
  - notification-service-pdb.yaml
  - ingress.yaml
