apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-hub

resources:
  - ../../base
  - ../../security

configMapGenerator:
  - name: platform-config
    envs:
      - config.env

secretGenerator:
  - name: platform-secrets
    envs:
      - secrets.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: frontend
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/frontend
    newTag: latest
  - name: community-api
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/community-api
    newTag: 20260307-uifix
  - name: api-gateway
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/api-gateway
    newTag: latest
  - name: auth-service
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/auth-service
    newTag: latest
  - name: profile-service
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/profile-service
    newTag: latest
  - name: media-service
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/media-service
    newTag: latest
  - name: notification-service
    newName: 656564335769.dkr.ecr.eu-central-1.amazonaws.com/notification-service
    newTag: latest
